### ISSUE TITLE
たまに落ちる

### ISSUE THREAD

**Issue by k-hatano** [k-hatano/tapchord#25]
App sometimes crashes

**Comment by k-hatano** [comment]
コードボタンを連打すると落ちる気がする。

**Comment by k-hatano** [comment]
再現性がない。

**Comment by k-hatano** [comment]
1回再現した。

**Comment by k-hatano** [comment]
指複数で素早く連打したらわりと落ちる。

**Comment by k-hatano** [comment]
ACRAの導入を要検討？

**Comment by k-hatano** [comment]
魚拓取ったり。
```
06-16 01:27:16.720: E/AndroidRuntime(20852): FATAL EXCEPTION: main
06-16 01:27:16.720: E/AndroidRuntime(20852): Process: jp.nita.tapchord, PID: 20852
06-16 01:27:16.720: E/AndroidRuntime(20852): java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for pause()
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at android.media.AudioTrack.native_pause(Native Method)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at android.media.AudioTrack.pause(AudioTrack.java:1200)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at jp.nita.tapchord.Sound.finish(Sound.java:295)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at jp.nita.tapchord.Sound.stop(Sound.java:59)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at jp.nita.tapchord.TapChordView.stop(TapChordView.java:1380)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at jp.nita.tapchord.TapChordView.onTouchEvent(TapChordView.java:872)
06-16 01:27:16.720: E/AndroidRuntime(20852): 	at android.view.View.dispatchTouchEvent(View.java:8464)
```

**Comment by k-hatano** [comment]
ほぼ変わらないが、エラーメッセージ。

```
07-25 15:54:10.443: E/AndroidRuntime(9944): FATAL EXCEPTION: main
07-25 15:54:10.443: E/AndroidRuntime(9944): Process: jp.nita.tapchord, PID: 9944
07-25 15:54:10.443: E/AndroidRuntime(9944): java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for pause()
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at android.media.AudioTrack.native_pause(Native Method)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at android.media.AudioTrack.pause(AudioTrack.java:1638)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.Sound.finish(Sound.java:295)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.Sound.release(Sound.java:63)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.TapChordView.release(TapChordView.java:1235)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.TapChordView.play(TapChordView.java:1211)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.TapChordView.actionDown(TapChordView.java:591)
07-25 15:54:10.443: E/AndroidRuntime(9944): 	at jp.nita.tapchord.TapChordView.onTouchEvent(TapChordView.java:778)
```

**Comment by k-hatano** [comment]
1.2.2で改善したとみていいでしょう。
Reopenする場合は再現条件を記載。
